export const INITIATE_LOGIN_STARTED = 'INITIATE_LOGIN_STARTED';
export const INITIATE_LOGIN_SUCCESS = 'INITIATE_LOGIN_SUCCESS';
export const INITIATE_LOGIN_FAILURE = 'INITIATE_LOGIN_FAILURE';
export const INITIATE_LOGOUT_STARTED = 'INITIATE_LOGOUT_STARTED';
export const INITIATE_LOGOUT_SUCCESS = 'INITIATE_LOGOUT_SUCCESS';
export const INITIATE_LOGOUT_FAILURE = 'INITIATE_LOGOUT_FAILURE';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
